// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Receipt struct {
	ReceiptID              pgtype.UUID
	UserID                 pgtype.UUID
	NameOfEstablishment    pgtype.Text
	Currency               pgtype.Text
	NumberOfItems          int32
	Subtotal               pgtype.Numeric
	TaxValue               pgtype.Numeric
	TaxNa                  pgtype.Bool
	TipValue               pgtype.Numeric
	TipNa                  pgtype.Bool
	AdditionalChargesValue pgtype.Numeric
	AdditionalChargesNa    pgtype.Bool
	Total                  pgtype.Numeric
	ImageData              []byte
	ImageContentType       pgtype.Text
	Status                 bool
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type ReceiptItem struct {
	ItemID       pgtype.UUID
	ReceiptID    pgtype.UUID
	Name         string
	Quantity     int32
	PricePerItem pgtype.Numeric
	TotalPrice   pgtype.Numeric
	CreatedAt    pgtype.Timestamptz
}

type User struct {
	UserID       pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
